#! /bin/sh

RCPSDATA=$RCPSROOT/data

mkdir $RCPSDATA/00_Model_Building
mkdir $RCPSDATA/00_Model_Building/1-D

DATADIR=$RCPSDATA/00_Model_Building/1-D

# Generation VP, VS, density (RO) logs
# to be used as Input in the reflectivity calculation (p_Rpanels program)
cp interf002.asc $DATADIR

cd $DATADIR

unif2 < interf002.asc \
  ninf=4 \
  nx=1 nz=15001 dz=0.4 \
  v00=3130.0,3050.0,3700.0,5000.0,3800.0 \
  > VP_z.ad

unif2 < interf002.asc \
  ninf=4 \
  nx=1 nz=15001 dz=0.4 \
  v00=1550.0,1750.0,2150.0,2800.0,2200.0 \
  > VS_z.ad

unif2 < interf002.asc \
  ninf=4 \
  nx=1 nz=15001 dz=0.4 \
  v00=2430.0,2220.0,2500.0,2200.0,2550.0 \
  > RO_z.ad

# SEG-Y Header
suaddhead n1=15001 <VP_z.ad | sushw key=dt a=400 > VP_z.su
suaddhead n1=15001 <VS_z.ad | sushw key=dt a=400 > VS_z.su
suaddhead n1=15001 <RO_z.ad | sushw key=dt a=400 > RO_z.su

#cat VP_z.ad VS_z.ad RO_z.ad > Elogs_z.ad
#suaddhead n1=8001 <Elogs_z.ad | sushw key=dt a=400 > Elogs_z.su

# Display
suwind < VP_z.su tmin=1.8 | \
  suxwigb legend=1 title="VP[m/s]" label1="Z[km]" &
suwind < VS_z.su tmin=1.8 | \
  suxwigb legend=1 title="VS[m/s]" label1="Z[km]" &
suwind < RO_z.su tmin=1.8 | \
  suxwigb legend=1 title="RO[kg/m3]" label1="Z[km]" &

suxwigb < VP_z.su legend=1 title="VP[m/s]" label1="Z[km]" &

#suwind < Elogs_z.su tmin=1.8 | \
#  suxwigb legend=1 title="VP, VS, RO" label1="Z[m]" &

