#! /bin/sh

RCPSDATA=$RCPSROOT/data

INPUTDIR=$RCPSDATA/00_Model_Building/1-D

mkdir $RCPSDATA/02_Synthetic_Seismograms
mkdir $RCPSDATA/02_Synthetic_Seismograms/1-D
DATADIR=$RCPSDATA/02_Synthetic_Seismograms/1-D

# Control parameters
nx=1
ny=1
nz=15001
dz=0.4
noffset=25
doffset=100.0
offset0=100.0

# Input data (logs or model in z)
trc_VP=$INPUTDIR/VP_z.ad
trc_VS=$INPUTDIR/VS_z.ad
trc_RO=$INPUTDIR/RO_z.ad

# Output data
trc_timePP=$DATADIR/timePP_z.ad
trc_timePS=$DATADIR/timePS_z.ad
trc_thetaPP=$DATADIR/thetaPP_z.ad
trc_thetaPS=$DATADIR/thetaPS_z.ad
trc_phi=$DATADIR/phi_z.ad
trc_RPP=$DATADIR/RPP_z.ad
trc_RPS=$DATADIR/RPS_z.ad

cd $DATADIR

p_Roffset_z $nx $ny $nz $dz \
            $noffset $doffset $offset0 \
            $trc_timePP $trc_timePS \
            $trc_thetaPP $trc_thetaPS $trc_phi \
            $trc_VP $trc_VS $trc_RO \
            $trc_RPP $trc_RPS

