#! /bin/sh

INPUTDIR=$RCPSROOT/data/00_Model_Building/1-D
DATADIR=$RCPSROOT/data/02_Synthetic_Seismograms/1-D

suaddhead n1=15001 <$INPUTDIR/VP_noisy_z.ad     | sushw key=dt a=400 >temp1.su
suximage <temp1.su cmap=hsv2 legend=1 title='VP noisy [m/s]' &


suaddhead n1=15001 <$DATADIR/ThetaPP_noisy_z.ad | sushw key=dt a=400 >temp2.su
suximage <temp2.su cmap=hsv2 legend=1 title='ThetaPP noisy [rad]' &

suaddhead n1=15001 <$DATADIR/ThetaPS_noisy_z.ad | sushw key=dt a=400 >temp3.su
suximage <temp3.su cmap=hsv2 legend=1 title='ThetaPS noisy [rad]' &

suaddhead n1=15001 <$DATADIR/Phi_noisy_z.ad     | sushw key=dt a=400 >temp4.su
suximage <temp4.su cmap=hsv2 legend=1 title='Phi noisy [rad]' &

suaddhead n1=15001 <$DATADIR/TwtPP_noisy_z.ad   | sushw key=dt a=400 >temp5.su
suximage <temp5.su cmap=hsv2 legend=1 title='P-P TWT noisy [s]' &

suaddhead n1=15001 <$DATADIR/TwtPS_noisy_z.ad   | sushw key=dt a=400 >temp6.su
suximage <temp6.su cmap=hsv2 legend=1 title='P-S TWT noisy [s]' &

suaddhead n1=15001 <$DATADIR/RPP_noisy_z.ad     | sushw key=dt a=400 >temp7.su
suxwigb <temp7.su legend=1 title='P-P Reflectivity noisy' &

suaddhead n1=15001 <$DATADIR/RPS_noisy_z.ad     | sushw key=dt a=400 >temp8.su
suxwigb <temp8.su legend=1 title='P-S Reflectivity noisy' &

rm temp*.su

