#! /bin/sh

INPUTDIR=$RCPSROOT/data/00_Model_Building/1-D
DATADIR=$RCPSROOT/data/02_Synthetic_Seismograms/1-D

suaddhead n1=15001 <$INPUTDIR/VP_z.ad     | sushw key=dt a=400 >temp1.su
suximage <temp1.su cmap=hsv2 legend=1 title='VP [m/s]' &


suaddhead n1=15001 <$DATADIR/ThetaPP_z.ad | sushw key=dt a=400 >temp2.su
suximage <temp2.su cmap=hsv2 legend=1 title='ThetaPP [rad]' &

suaddhead n1=15001 <$DATADIR/ThetaPS_z.ad | sushw key=dt a=400 >temp3.su
suximage <temp3.su cmap=hsv2 legend=1 title='ThetaPS [rad]' &

suaddhead n1=15001 <$DATADIR/Phi_z.ad     | sushw key=dt a=400 >temp4.su
suximage <temp4.su cmap=hsv2 legend=1 title='Phi [rad]' &

suaddhead n1=15001 <$DATADIR/TwtPP_z.ad   | sushw key=dt a=400 >temp5.su
suximage <temp5.su cmap=hsv2 legend=1 title='P-P TWT [s]' &

suaddhead n1=15001 <$DATADIR/TwtPS_z.ad   | sushw key=dt a=400 >temp6.su
suximage <temp6.su cmap=hsv2 legend=1 title='P-S TWT [s]' &

suaddhead n1=15001 <$DATADIR/RPP_z.ad     | sushw key=dt a=400 >temp7.su
suximage <temp7.su cmap=hsv2 legend=1 title='P-P Reflectivity' &

suaddhead n1=15001 <$DATADIR/RPS_z.ad     | sushw key=dt a=400 >temp8.su
suximage <temp8.su cmap=hsv2 legend=1 title='P-S Reflectivity' &

rm temp*.su

