#! /bin/sh

RCPSDATA=$RCPSROOT/data

mkdir $RCPSDATA/00_Model_Building
mkdir $RCPSDATA/00_Model_Building/1-D

DATADIR=$RCPSDATA/00_Model_Building/1-D

# Generation VP, VS, density (RO) logs
# to be used as Input in the reflectivity calculation (p_Rpanels program)
cp interf001.asc $DATADIR

cd $DATADIR

unif2 < interf001.asc \
  ninf=5 \
  nx=1 nz=1001 dz=4.0 \
  v00=1500.0,3130.0,3050.0,3700.0,5000.0,3800.0 \
  > VP_twt.ad

unif2 < interf001.asc \
  ninf=5 \
  nx=1 nz=1001 dz=4.0 \
  v00=0.0,1550.0,1750.0,2150.0,2800.0,2200.0 \
  > VS_twt.ad

unif2 < interf001.asc \
  ninf=5 \
  nx=1 nz=1001 dz=4.0 \
  v00=1000.0,2430.0,2220.0,2500.0,2200.0,2550.0 \
  > RO_twt.ad

# SEG-Y Header
suaddhead n1=1001 <VP_twt.ad | sushw key=dt a=4000 > VP_twt.su
suaddhead n1=1001 <VS_twt.ad | sushw key=dt a=4000 > VS_twt.su
suaddhead n1=1001 <RO_twt.ad | sushw key=dt a=4000 > RO_twt.su
 
# Display
suwind < VP_twt.su tmin=2.5 | \
  suximage legend=1 title="VP[m/s]" label1="twt[s]" &
suwind < VS_twt.su tmin=2.5 | \
  suximage legend=1 title="VS[m/s]" label1="twt[s]" &
suwind < RO_twt.su tmin=2.5 | \
  suximage legend=1 title="RO[kg/m3]" label1="twt[s]" &

