#! /bin/sh

RCPSDATA=$RCPSROOT/data

mkdir $RCPSDATA/00_Model_Building
mkdir $RCPSDATA/00_Model_Building/3-D

DATADIR=$RCPSDATA/00_Model_Building/3-D

option=1
Nx=201
Ny=211
dx=50.0
dy=50.0
fx=0.0
fy=0.0
zref=1010.0
x0=5000.0
y0=5000.0
A=-210.0
sigma=500.0
horiz=$DATADIR/Horiz_E.asc
tempfile=$DATADIR/temp.ad

p_horizon2D $option $Nx $Ny $dx $dy $fx $fy $zref $x0 $y0 $A $sigma >$horiz

a2b n1=1 <$horiz >$tempfile

suaddhead n1=$Ny <$tempfile | sushw key=dt a=1000 | \
  suximage wbox=1000 d1=$dy d2=$dx cmap=hsv6 legend=1 title=$horiz &


