# ------------------------------------------------------------
# Zoeppritz calculations
# ------------------------------------------------------------
from rsf.proj import *

Flow('RPPtrace','',
  '''
  zoeppritz 
  na=40 da=2.0 a0=0 \
  vp1=3130 vs1=1550 rho1=2.43 \
  vp2=3050 vs2=1750 rho2=2.22
  ''')

Flow('RPStrace','',
  '''
  zoeppritz outp=n
  na=40 da=2.0 a0=0 \
  vp1=3130 vs1=1550 rho1=2.43 \
  vp2=3050 vs2=1750 rho2=2.22
  ''')

Result('RPPtrace','graph title=Rpp')
Result('RPStrace','graph title=Rps')


End()

