# ------------------------------------------------------------
# Zoeppritz calculations
# ------------------------------------------------------------
from rsf.proj import *

Flow('RPPtrace','',
  '''
  zoeppritz 
  na=40 da=2.0 a0=0 \
  vp1=3500 vs1=1750 rho1=2.45 \
  vp2=5000 vs2=2650 rho2=2.45
  ''')

Flow('RPStrace','',
  '''
  zoeppritz outp=n
  na=40 da=2.0 a0=0 \
  vp1=3500 vs1=1750 rho1=2.45 \
  vp2=5000 vs2=2650 rho2=2.45
  ''')

Result('RPPtrace','graph title=Rpp')
Result('RPStrace','graph title=Rps')


End()

