# ------------------------------------------------------------
# Zoeppritz calculations
# ------------------------------------------------------------
from rsf.proj import *

Flow('RPPtrace','',
  '''
  zoeppritz 
  na=40 da=2.0 a0=0 \
  vp1=2150 vs1=860 rho1=2200 \
  vp2=1750 vs2=1250 rho2=1950
  ''')

Flow('RPStrace','',
  '''
  zoeppritz outp=n
  na=40 da=2.0 a0=0 \
  vp1=2150 vs1=860 rho1=2200 \
  vp2=1750 vs2=1250 rho2=1950
  ''')

Result('RPPtrace','graph title=Rpp')
Result('RPStrace','graph title=Rps')


End()

