#! /bin/sh

RCPSDATA=$RCPSROOT/data

mkdir $RCPSDATA/01_Reflectivity
DATADIR=$RCPSDATA/01_Reflectivity

cd $DATADIR

option=1
na=40
da=2.0
a0=0
Vp_upper=2150.0
Vs_upper=850.0
Ro_upper=2200.0
Vp_lower=1750.0
Vs_lower=1250.0
Ro_lower=1950.0
fileRefl=Approx_RPP_RPS_g3.asc

#p_RPP_RPS $na $da $a0 $Vp_upper $Vs_upper $Ro_upper $Vp_lower $Vs_lower $Ro_lower $fileRefl

p_forward $na $da $a0 $Vp_upper $Vs_upper $Ro_upper $Vp_lower $Vs_lower $Ro_lower $fileRefl

