# ------------------------------------------------------------
# Zoeppritz calculations
# ------------------------------------------------------------
from rsf.proj import *

Flow('RPPtrace','',
  '''
  zoeppritz 
  na=40 da=2.0 a0=0 \
  vp1=3600 vs1=2400 rho1=2600 \
  vp2=4500 vs2=2500 rho2=2100
  ''')

Flow('RPStrace','',
  '''
  zoeppritz outp=n
  na=40 da=2.0 a0=0 \
  vp1=3600 vs1=2400 rho1=2600 \
  vp2=4500 vs2=2500 rho2=2100
  ''')

Result('RPPtrace','graph title=Rpp')
Result('RPStrace','graph title=Rps')


End()

