#! /bin/sh

RCPSDATA=$RCPSROOT/data

DATADIR=$RCPSDATA/02_Synthetic_Seismograms/1-D

# Control parameters
nx=1
ny=1
nt=3001
dt=0.002
noffset=25
doffset=100.0
offset0=100.0

# Input data
trc_NmoPP_t=$DATADIR/NmoPP_t.ad
trc_NmoPS_t=$DATADIR/NmoPS_t.ad
trc_SynthPP_t=$DATADIR/SynthPP_t.ad
trc_SynthPS_t=$DATADIR/SynthPS_t.ad
trc_ThetaPP_t=$DATADIR/ThetaPP_t.ad
trc_ThetaPS_t=$DATADIR/ThetaPS_t.ad

# Output
trc_SynthPP_to=$DATADIR/SynthPP_to.ad
trc_SynthPS_to=$DATADIR/SynthPS_to.ad
trc_ThetaPP_to=$DATADIR/ThetaPP_to.ad
trc_ThetaPS_to=$DATADIR/ThetaPS_to.ad

cd $DATADIR

p_NMO_PpPs $nx $ny $nt $dt \
           $noffset $doffset $offset0 \
           $trc_NmoPP_t $trc_NmoPS_t \
           $trc_SynthPP_t $trc_SynthPS_t \
           $trc_ThetaPP_t $trc_ThetaPS_t \
           $trc_SynthPP_to $trc_SynthPS_to \
           $trc_ThetaPP_to $trc_ThetaPS_to



